
[Network]
#type rpc or channel
Type="channel"
CAFile="/home/dyy/sdk/ca.crt"
Cert="/home/dyy/sdk/sdk.crt"
Key="/home/dyy/sdk/sdk.key"
# if the certificate context is not empty, use it, otherwise read from the certificate file
# multi lines use triple quotes
CAContext=''''''
KeyContext=''''''
CertContext=''''''

[[Network.Connection]]
NodeURL="192.168.204.110:20200"
GroupID=1
# [[Network.Connection]]
# NodeURL="127.0.0.1:20200"
# GroupID=2

[Account]
# only support PEM format for now
KeyFile="/home/dyy/accounts/0x42c743e1e59084b603b0c286348084147696f7fc.pem"

[Chain]
ChainID=1
SMCrypto=false

[log]
Path="./"
